crypto_dbt_project:
  target: dev

  outputs:
    dev:
      type: clickhouse
      schema: crypto_analytics
      host: clickhouse
      port: 8123
      user: admin
      password: admin123
      secure: false
      verify: false
      driver: http