name: CI/CD - dbt Tests & Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'screenshots/**'
      - 'architecture/**'
      - '*.md'
      
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'screenshots/**'
      - 'architecture/**'
      - '*.md'

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run dbt tests on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/real-time-crypto-analytics-pipeline
            docker compose exec -T airflow bash -c "
              cd /opt/project/crypto_dbt_project &&
              python -c \"from dbt.cli.main import dbtRunner; result = dbtRunner().invoke(['test', '--profiles-dir', '.']); exit(0 if result.success else 1)\"
            "

  deploy:
    runs-on: ubuntu-latest
    needs: dbt-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/real-time-crypto-analytics-pipeline
            git pull
            docker compose up -d --build streamlit_dashboard
            /home/ubuntu/run_dbt.sh# updated
